### ISSUE TITLE
This is really great

### ISSUE THREAD

**Issue by tokensalad** [avilaton/node-spss#1]
Is there anyway to modify the 
'parser.tap('remaining_dict', function () {'
So that it retrieves the value labels for all the variables rather than just the first one that has value labels?
If you could point me in the direction of the answer It would be much appreciated

**Comment by avilaton** [comment]
I stopped hacking on this but most of the information I had taken from a GNU package that was supposed to be able to read this format. Not sure I could help you any further but it is a hackable project.

**Comment by avilaton** [comment]
there is a perl script taken from somewhere else which you find in this repo that used to parse the file format more extensively.

**Comment by tokensalad** [comment]
Thanks for getting back to me so quickly, really appreciate it and at the very least you have shown me what is possible.

**Comment by tokensalad** [comment]
Is there any chance I could pay you to finish the project? A bit cheeky I know, but I thought I would ask.

**Comment by avilaton** [comment]
Contact me over at avila.gas@gmail.com and we can talk about it for sure.
